name: "Deploy PowerShell docs"

description: "Deploys Powershell documentation to remote Server"

branding:
  icon: "upload-cloud"
  color: "red"

inputs:
  project_id:
    description: "ID of project"
    required: true
  api_key:
    description: "API key"
    required: true
  source_type:
    description: "Source type (script / module)"
    required: false
    default: "script"
  source_dir:
    description: "Directory location of the PowerShell scripts"
    required: false
    default: ""

outputs:
  doc_url:
    description: "Url of the online documentation"

runs:
  using: "docker"
  image: "docker://justiniven/ps_docs_online-deploy:dev"
