name: "Deploy PowerShell docs"

description: "Deploys Powershell documentation to remote Server"

branding:
  icon: "upload-cloud"
  color: "red"

inputs:
  api_token:
    description: "API token"
    required: true
  root_dir:
    description: "Directory location of the PowerShell scripts"
    required: true
    default: ""

outputs:
  doc_url:
    description: "Url of the online documentation"

runs:
  using: "docker"
  image: "docker://justiniven/ps_docs_online-deploy"
